############### MQTT
mqtt:
    container_name : mqtt
    image: eclipse-mosquitto
    restart: always
    volumes: 
        - $HOME/mosquitto/config:/mosquitto/config
        - $HOME/mosquitto/data:/mosquitto/data
        - $HOME/mosquitto/log:/mosquitto/log
    ports:
        - 1883:1883
        - 9001:9001


